### ISSUE TITLE
[BUG] Missing `-` in docker-compose and missing package installation instructions

### ISSUE THREAD

**Issue by WORMSTweaker** [wanjohiryan/Arc3dia#11]
**Describe the bug**
A `-` is missing in the proposed docker-compose file. Additionally, it is not specified that the `nvidia-container-toolkit` package is required to use the container

**To Reproduce**
1. Copy/clone the docker-compose.yml file in a folder
2. Run `docker compose up -d`
3. Observe an error about `devices` not being a list
4. After having fixed the list, and trying again, observe an error about the device driver `""` not being selected

**Expected behavior**
Container starting and using the specified GPU

**Screenshots**
![qwantify](https://user-images.githubusercontent.com/1344245/207665357-cbca63bb-cab5-4e5a-a13e-6320013cd61a.gif)

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser: Firefox
 - Version: 107.0.1

**Additional context**
I installed the `nvidia-container-toolkit` on my system. After this, the container run successfully (but did not run the game, that is for another issue and probably because I'm on Linux)

**Comment by wanjohiryan** [comment]
Thanks for highlighting that. I forgot to mention that nvidia-docker and nvidia-container-toolkit.

I will definitely update the README.

Now tell me about the game. 
(1) Does it run on DirectX 11 or lower? 
(2) Does it require any extra libraries? (probably VSRedist or .Net framework)

> but did not run the game, that is for another issue and probably because I'm on Linux

I have ran all my games on linux with this. But as highlighted here #2 only games running on DX12 are working (until i get a workaround to installing DXVK on the fly)

**Comment by wanjohiryan** [comment]
Hi @WORMSTweaker How was your first experience with qwantify?

What would you like to be added or removed? Probably better documentation, I guess :)

**Comment by WORMSTweaker** [comment]
Well, apart from the little docker file problem, the install was relatively easy, I got in the interface quickly but was unable to log in, probably because the game I chose didn't run. It is not really specified what system this can run on, but I can guess it was made with windows in mind, since the game executable is a .exe
Or can it run software on Linux in some way? If this the case then it is not really explained or specified in the readme, so a little more of documentation is always appreciated yes.

Also, the interface still has the n.eko branding, but I guess this is because this project is still in its infancy! If this goes as planned, then your project is quite promising!

**Comment by wanjohiryan** [comment]
Thanks for your feedback and kind words.

>Or can it run software on Linux in some way?

Naah, it is not limited to linux. It runs on docker, so pretty much anywhere that docker can run, it can run: Raspberry Pie, Linux or windows.

I am working on the documentation part. And in a day or two, we might merge it to the master branch.

>Also, the interface still has the n.eko branding, but I guess this is because this project is still in its infancy! If this goes as planned, then your project is quite promising!

Yeah am working on that. Amongst other things. Hopefully you'll be here to try out the v1 :)
