### ISSUE TITLE
ReadMe contradicts itself?

### ISSUE THREAD

**Issue by JD-The-65th** [wanjohiryan/Arc3dia#17]
Early on in the readme, it has this to say:

> "Official Support for AMD and Intel Gpus"

But later on in said Readme, it contradicts itself....

> "qwantify has not been tested on AMD and Intel GPUs. This might present unknown issues."

Which one is it? Please, fix this in the readme.

**Comment by wanjohiryan** [comment]
Nice catch.  

I will fix the ReadMe

qwantify has only been officially tested on Nvidia GPUs only. 

But it can work on any GPU (in theory). This has not been tested though.

Do check out #8

**Comment by SamKr** [comment]
Are you sure you added enough questionmarks in the subject @JD-The-65th? Might want to add a few more to make sure.

**Comment by JD-The-65th** [comment]
> Are you sure you added enough questionmarks in the subject @JD-The-65th? Might want to add a few more to make sure.

Yeah, sorry bout that. I was just really confused on how something like this gets missed.

**Comment by wanjohiryan** [comment]
Hi @JD-The-65th

Sorry for the delay, but I have finally addressed this issue in #24 which has been merged to master.

Feel free to reopen this issue if you find it unsatisfactory.

>Happy New Year 🥳
