### ISSUE TITLE
Running linux based games with neko-rooms

### ISSUE THREAD

**Issue by impromedia** [wanjohiryan/Arc3dia#18]
I want to run an Ubuntu game packaged in an AppImage. 

I've changed the file /etc/entrypoint.sh to point to the game: 

#!/bin/bash -e
 #Add VirtualGL directories to path
export PATH="${PATH}:/opt/VirtualGL/bin"

 Use VirtualGL to run wine with OpenGL if the GPU is available, otherwise use barebone wine
if [ -n "$(nvidia-smi --query-gpu=uuid --format=csv | sed -n 2p)" ]; then
  export VGL_DISPLAY="${VGL_DISPLAY:-egl}"
  export VGL_REFRESHRATE="$REFRESH"
  cd /games && vglrun +wm game.AppImage --appimage-extract-and-run
else
  cd /games && game.AppImage --appimage-extract-and-run
fi

it seems that the GPU are not available on the docker even I've installed nvidia-docker and Nvidia container toolkit
I'm using neeko-rooms to instantiate the qwantify sessions.
it is a work around to enable the GPU's in the container when it is started by neko-rooms?

**Comment by wanjohiryan** [comment]
Hi @impromedia 

I haven't looked at neko-rooms yet. But this seems interesting.

What happens when you ssh into the container(s) and run `nvidia-smi` (assuming you are using a Nvidia gpu)?

**Comment by impromedia** [comment]
Thank you for your fast replay. If I run nvidia-smi inside the container it is working:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. 
|                               |                      |               MIG M. |
|   0  Tesla T4            On   | 00000000:0B:00.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |     70MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:13:00.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |     25MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
+-----------------------------------------------------------------------------+

I've extracted the app image and when I start it, I get "segmentation fault (core dumped)" error
The app need minimum 8GB to run, maybe this is the issue.
How to increase it (on the host I have 320 GB) ?

**Comment by impromedia** [comment]
It looks that the app Interface is allowed to use only 2GB memory.

![image](https://user-images.githubusercontent.com/40540482/210138195-61c44c3b-b93b-457c-a74b-a21cc6eb05f9.png)

**Comment by wanjohiryan** [comment]
There seems to be no issue with the containers accessing your Nvidia GPUs.

>It looks that the app Interface is allowed to use only 2GB memory.

Try changing the shared memory `shm` to '8gb' in the docker-compose.yaml and see whether that helps

```bash
shm_size: '8gb' 
```
