### ISSUE TITLE
Docker compose conf dont work

### ISSUE THREAD

**Issue by kiam001** [wanjohiryan/Arc3dia#31]
I try it in wsl, it dont work correct.

d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:13,836 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:14,037 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:14,238 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:14,438 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:14,639 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:14,840 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:15,041 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:15,241 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM INF Setting new connection state: Failed module=webrtc submodule=pion subsystem=ice
d-qwantify-1  | 11:04AM INF ICE connection state changed: failed module=webrtc submodule=pion subsystem=pc
d-qwantify-1  | 11:04AM INF connection state has changed connection_state=failed module=webrtc
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:15,241 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM INF peer connection state changed: failed module=webrtc submodule=pion subsystem=pc
d-qwantify-1  | 11:04AM WRN peer failed id=fFML5HZ5IXvDvjNptbXKdO3b6YPkOAln module=webrtc
d-qwantify-1  | 11:04AM INF Setting new connection state: Closed module=webrtc submodule=pion subsystem=ice
d-qwantify-1  | 11:04AM INF peer connection state changed: closed module=webrtc submodule=pion subsystem=pc
d-qwantify-1  | 11:04AM INF ICE connection state changed: closed module=webrtc submodule=pion subsystem=pc
d-qwantify-1  | 11:04AM INF connection state has changed connection_state=closed module=webrtc
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:15,242 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM INF peer closed id=fFML5HZ5IXvDvjNptbXKdO3b6YPkOAln module=webrtc
d-qwantify-1  | 11:04AM WRN Failed to start manager: connecting canceled by caller module=webrtc submodule=pion subsystem=pc
d-qwantify-1  | 11:04AM WRN Failed to start SCTP: DTLS not established module=webrtc submodule=pion subsystem=pc
d-qwantify-1  | 11:04AM WRN undeclaredMediaProcessor failed to open SrtpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc
d-qwantify-1  | 11:04AM WRN undeclaredMediaProcessor failed to open SrtcpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:15,287 DEBG 'pulseaudio' stdout output:
d-qwantify-1  | I: [pulseaudio] source-output.c: Freeing output 0 "Record Stream"
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:15,288 DEBG 'pulseaudio' stdout output:
d-qwantify-1  | I: [pulseaudio] client.c: Freed 0 "neko"
d-qwantify-1  | I: [pulseaudio] protocol-native.c: Connection died.
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:15,288 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM INF destroying pipeline module=capture submodule=stream-sink video_id=audio
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:15,288 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM INF last listener, stopping module=capture submodule=stream-sink video_id=audio
d-qwantify-1  |
d-qwantify-1  | 2023-01-09 11:04:15,521 DEBG 'neko' stdout output:
d-qwantify-1  | 11:04AM INF destroying pipeline module=capture submodule=stream-sink video_id=video
d-qwantify-1  | 11:04AM INF last listener, stopping module=capture submodule=stream-sink video_id=video
d-qwantify-1  | 11:04AM INF destroying session module=session session_id=fFML5HZ5IXvDvjNptbXKdO3b6YPkOAln
d-qwantify-1  |

**Comment by wanjohiryan** [comment]
Hi @kiam001 

This error is intentional, as we are dropping WebRTC in favor of QUIC in #22 

>There are some breaking changes i have already pushed to the master branch, that could be causing this

Could you try running qwantify in 3 days time? I am yet to merge the pull request.

Sorry for any inconvenience(s).

> a messy fix would be this [docker-compose.yaml](https://github.com/wanjohiryan/qwantify/blob/e3b11231dfe5d29d4f5eba8a733856d1cbfaaac7/docker-compose.yaml)

**Comment by kiam001** [comment]
All cool,

nice for answering.

THX for cool Projekt :), i will hope i will love it <3

Take time :) and cooding good

**Comment by wanjohiryan** [comment]
Thanks, 

Have a nice time too
