### ISSUE TITLE
Add a community for qwantify

### ISSUE THREAD

**Issue by Makergear25** [wanjohiryan/Arc3dia#55]
You should start a discord or some other community for qwantify as I and I am sure others are interested in how it is going.

**Comment by wanjohiryan** [comment]
Hi @Makergear25 

Sorry for the long silence, i had thought of this a while back... I needed a nudge :)

This is being addressed by #56

Anything else you would like help with?

**Comment by Makergear25** [comment]
Nope thats it glad to see you made one

**Comment by wanjohiryan** [comment]
Okay, closing this issue
